export interface ClientMonitor {
  id: string;
  name: string;
  score: number;
  status: 'ONLINE' | 'DEGRADED' | 'OFFLINE';
  uptimeText: string;
  connectionType: 'wifi' | 'lan';
  connectionName: string; // e.g. "CozlinManase", "Wired LAN", "KONNECT", "Mara"
  ispName: string; // e.g. "Airtel Kenya", "Faiba", "MTN Business Kenya", "Safaricom", "IPXO"
  isFavorite: boolean;
  isHero?: boolean;
  badgeType?: 'gold-crest' | 'heart';
  subNote?: string;
  // Sub-scores matching the 3 orb glyphs
  responsivenessScore: number;
  reliabilityScore: number;
  speedScore: number;
  // Detailed telemetry matching images 1 & 2
  telemetry?: {
    lagRouterMs: number;
    lagInternetMs: number;
    downloadMbps: number;
    uploadMbps: number;
    downloadTimeAgo?: string;
    uploadTimeAgo?: string;
    signalDbm: number;
    band: string;
    channel: number;
    receiveRateMbps: number;
    transmitRateMbps: number;
    bssid: string;
    macAddress: string;
    physicalLayer: string;
    security: string;
    os: string;
    orbSensorVersion: string;
    orbAppVersion: string;
    privateIp: string;
    publicIp: string;
    networkEndpoint: string;
    uptimeDuration: string;
    reliabilityBars?: boolean[];
  };
}

export interface OrbLiveData {
  id?: string;
  cloneId?: string;
  name?: string;
  score?: number;
  status?: 'ONLINE' | 'DEGRADED' | 'OFFLINE';
  connection?: string;
  isp?: string;
  location?: string;
  latencyMs?: number | string;
  downloadMbps?: number | null;
  uploadMbps?: number | null;
  uptime?: string;
  components?: {
    responsiveness?: number;
    reliability?: number;
    bandwidth?: number;
  };
}

declare global {
  interface Window {
    __ORB_DATA__?: OrbLiveData;
  }
}

export const INITIAL_CLIENTS: ClientMonitor[] = [
  // Black-Bird-HQ9 (from Image 1 & 2)
  {
    id: 'blackbird',
    name: 'Black-Bird-HQ9',
    score: 94,
    status: 'ONLINE',
    uptimeText: '2 hours',
    connectionType: 'wifi',
    connectionName: 'KONNECT',
    ispName: 'MTN Business Kenya',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 91,
    reliabilityScore: 100,
    speedScore: 96,
    telemetry: {
      lagRouterMs: 3,
      lagInternetMs: 29,
      downloadMbps: 370,
      uploadMbps: 256,
      downloadTimeAgo: 'an hour ago',
      uploadTimeAgo: 'an hour ago',
      signalDbm: -53,
      band: '5 GHz (5745 MHz)',
      channel: 149,
      receiveRateMbps: 780,
      transmitRateMbps: 866,
      bssid: '24****F0',
      macAddress: 'c8****34',
      physicalLayer: '802.11ac',
      security: 'Open',
      os: 'Windows',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '10.11.0.0',
      publicIp: '217.199.144.40',
      networkEndpoint: 'Nairobi, Nairobi County',
      uptimeDuration: '2:34 hrs',
    },
  },
  // Column 1 - Top Card (Hero Card from first screenshot)
  {
    id: 'cozlins',
    name: 'cozlins',
    score: 86,
    status: 'ONLINE',
    uptimeText: '2 hours',
    connectionType: 'wifi',
    connectionName: 'CozlinManase',
    ispName: 'Airtel Kenya',
    isFavorite: true,
    isHero: true,
    badgeType: 'gold-crest',
    responsivenessScore: 88,
    reliabilityScore: 95,
    speedScore: 84,
    telemetry: {
      lagRouterMs: 4,
      lagInternetMs: 32,
      downloadMbps: 94,
      uploadMbps: 42,
      downloadTimeAgo: '30 mins ago',
      uploadTimeAgo: '30 mins ago',
      signalDbm: -58,
      band: '5 GHz (5200 MHz)',
      channel: 40,
      receiveRateMbps: 650,
      transmitRateMbps: 650,
      bssid: '48****A2',
      macAddress: 'd4****12',
      physicalLayer: '802.11ac',
      security: 'WPA2-PSK',
      os: 'macOS',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.1.105',
      publicIp: '197.237.142.88',
      networkEndpoint: 'Nairobi, Nairobi County',
      uptimeDuration: '2:15 hrs',
    },
  },
  // Column 2 - Row 1
  {
    id: 'bbhouse',
    name: 'BBHouse Client Monitor',
    score: 86,
    status: 'ONLINE',
    uptimeText: '7 hours',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Faiba',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 92,
    reliabilityScore: 98,
    speedScore: 86,
    telemetry: {
      lagRouterMs: 1,
      lagInternetMs: 14,
      downloadMbps: 124,
      uploadMbps: 98,
      downloadTimeAgo: '2 hours ago',
      uploadTimeAgo: '2 hours ago',
      signalDbm: -40,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: 'a0****88',
      physicalLayer: '1000BASE-T',
      security: 'Wired 802.1X',
      os: 'Ubuntu Linux',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '10.0.0.45',
      publicIp: '41.90.114.23',
      networkEndpoint: 'Nairobi, Westlands',
      uptimeDuration: '7:42 hrs',
    },
  },
  // Column 3 - Row 1
  {
    id: 'brookeveg',
    name: 'BrookeVeg Muthaite Client Monitor',
    score: 88,
    status: 'ONLINE',
    uptimeText: '5 hours',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Faiba',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 90,
    reliabilityScore: 97,
    speedScore: 89,
    telemetry: {
      lagRouterMs: 1,
      lagInternetMs: 16,
      downloadMbps: 148,
      uploadMbps: 110,
      downloadTimeAgo: '4 hours ago',
      uploadTimeAgo: '4 hours ago',
      signalDbm: -42,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: 'b2****99',
      physicalLayer: '1000BASE-T',
      security: 'Wired',
      os: 'Windows 11',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.10.22',
      publicIp: '41.90.108.52',
      networkEndpoint: 'Nairobi, Muthaiga',
      uptimeDuration: '5:18 hrs',
    },
  },
  // Column 1 - Row 2
  {
    id: 'mara',
    name: 'Mara-Monitoring',
    score: 88,
    status: 'ONLINE',
    uptimeText: 'a day',
    connectionType: 'wifi',
    connectionName: 'Mara',
    ispName: 'Safaricom Business',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 89,
    reliabilityScore: 99,
    speedScore: 87,
    telemetry: {
      lagRouterMs: 5,
      lagInternetMs: 22,
      downloadMbps: 88,
      uploadMbps: 54,
      downloadTimeAgo: '6 hours ago',
      uploadTimeAgo: '6 hours ago',
      signalDbm: -55,
      band: '5 GHz (5240 MHz)',
      channel: 48,
      receiveRateMbps: 580,
      transmitRateMbps: 580,
      bssid: '12****E8',
      macAddress: '78****44',
      physicalLayer: '802.11ax',
      security: 'WPA3',
      os: 'Windows',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '172.16.1.4',
      publicIp: '105.163.2.14',
      networkEndpoint: 'Nairobi, Upper Hill',
      uptimeDuration: '24:12 hrs',
    },
  },
  // Column 2 - Row 2
  {
    id: 'gicheha',
    name: 'Gicheha Client Monitor',
    score: 91,
    status: 'ONLINE',
    uptimeText: '4 hours',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Safaricom',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 95,
    reliabilityScore: 99,
    speedScore: 92,
    telemetry: {
      lagRouterMs: 1,
      lagInternetMs: 11,
      downloadMbps: 210,
      uploadMbps: 160,
      downloadTimeAgo: '3 hours ago',
      uploadTimeAgo: '3 hours ago',
      signalDbm: -41,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: 'c4****71',
      physicalLayer: '1000BASE-T',
      security: 'Wired',
      os: 'Windows 10',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.8.55',
      publicIp: '105.160.78.19',
      networkEndpoint: 'Kiambu, Ruiru',
      uptimeDuration: '4:02 hrs',
    },
  },
  // Column 3 - Row 2 (Amber 62)
  {
    id: 'ichaweri',
    name: 'Ichaweri Client Monitor',
    score: 62,
    status: 'ONLINE',
    uptimeText: '19 hours',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'IPXO',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 58,
    reliabilityScore: 65,
    speedScore: 61,
    telemetry: {
      lagRouterMs: 14,
      lagInternetMs: 84,
      downloadMbps: 24,
      uploadMbps: 8,
      downloadTimeAgo: '12 hours ago',
      uploadTimeAgo: '12 hours ago',
      signalDbm: -72,
      band: 'Ethernet 100Mbps',
      channel: 1,
      receiveRateMbps: 100,
      transmitRateMbps: 100,
      bssid: 'N/A (Wired)',
      macAddress: 'e8****29',
      physicalLayer: '100BASE-TX',
      security: 'Wired',
      os: 'Linux Debian',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.1.18',
      publicIp: '185.220.101.5',
      networkEndpoint: 'Gatundu, Kiambu',
      uptimeDuration: '19:40 hrs',
    },
  },
  // Column 2 - Row 3 (Offline)
  {
    id: 'muthaiga',
    name: 'Muthaiga III Client Monitor',
    score: 89,
    status: 'OFFLINE',
    uptimeText: 'a month',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Faiba',
    isFavorite: true,
    badgeType: 'heart',
    subNote: 'showing last reported score',
    responsivenessScore: 0,
    reliabilityScore: 0,
    speedScore: 89,
    telemetry: {
      lagRouterMs: 0,
      lagInternetMs: 0,
      downloadMbps: 0,
      uploadMbps: 0,
      downloadTimeAgo: '32 days ago',
      uploadTimeAgo: '32 days ago',
      signalDbm: 0,
      band: 'Disconnected',
      channel: 0,
      receiveRateMbps: 0,
      transmitRateMbps: 0,
      bssid: 'N/A',
      macAddress: '3c****f2',
      physicalLayer: 'None',
      security: 'Wired',
      os: 'Windows Server',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '10.10.1.20',
      publicIp: '41.90.112.90',
      networkEndpoint: 'Nairobi, Muthaiga',
      uptimeDuration: '0 hrs (Offline)',
    },
  },
  // Column 3 - Row 3
  {
    id: 'seaview',
    name: 'Sea View Client Monitor',
    score: 82,
    status: 'ONLINE',
    uptimeText: 'an hour',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Faiba',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 84,
    reliabilityScore: 92,
    speedScore: 81,
    telemetry: {
      lagRouterMs: 2,
      lagInternetMs: 38,
      downloadMbps: 72,
      uploadMbps: 39,
      downloadTimeAgo: '45 mins ago',
      uploadTimeAgo: '45 mins ago',
      signalDbm: -48,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: '88****10',
      physicalLayer: '1000BASE-T',
      security: 'Wired',
      os: 'macOS Sonoma',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.2.14',
      publicIp: '41.90.99.11',
      networkEndpoint: 'Mombasa, Nyali',
      uptimeDuration: '1:12 hrs',
    },
  },
  // Peeking row
  {
    id: 'karen-hub',
    name: 'Karen Hub Client Monitor',
    score: 94,
    status: 'ONLINE',
    uptimeText: '3 days',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Safaricom',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 96,
    reliabilityScore: 100,
    speedScore: 94,
    telemetry: {
      lagRouterMs: 1,
      lagInternetMs: 9,
      downloadMbps: 250,
      uploadMbps: 180,
      downloadTimeAgo: '1 day ago',
      uploadTimeAgo: '1 day ago',
      signalDbm: -39,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: '2a****19',
      physicalLayer: '1000BASE-T',
      security: 'Wired',
      os: 'Ubuntu 24.04',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '10.0.10.15',
      publicIp: '105.161.12.44',
      networkEndpoint: 'Nairobi, Karen',
      uptimeDuration: '72:10 hrs',
    },
  },
  {
    id: 'lavington',
    name: 'Lavington Point Monitor',
    score: 87,
    status: 'ONLINE',
    uptimeText: '12 hours',
    connectionType: 'lan',
    connectionName: 'Wired LAN',
    ispName: 'Faiba',
    isFavorite: true,
    badgeType: 'heart',
    responsivenessScore: 89,
    reliabilityScore: 96,
    speedScore: 86,
    telemetry: {
      lagRouterMs: 2,
      lagInternetMs: 18,
      downloadMbps: 110,
      uploadMbps: 85,
      downloadTimeAgo: '5 hours ago',
      uploadTimeAgo: '5 hours ago',
      signalDbm: -45,
      band: 'Ethernet 1Gbps',
      channel: 1,
      receiveRateMbps: 1000,
      transmitRateMbps: 1000,
      bssid: 'N/A (Wired)',
      macAddress: '74****63',
      physicalLayer: '1000BASE-T',
      security: 'Wired',
      os: 'Windows 11',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.0.8',
      publicIp: '41.90.88.76',
      networkEndpoint: 'Nairobi, Lavington',
      uptimeDuration: '12:05 hrs',
    },
  },
  {
    id: 'nyali',
    name: 'Nyali Coastal Monitor',
    score: 79,
    status: 'ONLINE',
    uptimeText: '6 hours',
    connectionType: 'wifi',
    connectionName: 'Nyali-5G',
    ispName: 'Airtel Kenya',
    isFavorite: false,
    badgeType: 'heart',
    responsivenessScore: 78,
    reliabilityScore: 88,
    speedScore: 76,
    telemetry: {
      lagRouterMs: 8,
      lagInternetMs: 44,
      downloadMbps: 58,
      uploadMbps: 22,
      downloadTimeAgo: '2 hours ago',
      uploadTimeAgo: '2 hours ago',
      signalDbm: -64,
      band: '5 GHz (5180 MHz)',
      channel: 36,
      receiveRateMbps: 433,
      transmitRateMbps: 433,
      bssid: '90****B1',
      macAddress: '42****85',
      physicalLayer: '802.11ac',
      security: 'WPA2',
      os: 'Windows 10',
      orbSensorVersion: 'v1.5.5',
      orbAppVersion: '1.5.5',
      privateIp: '192.168.100.12',
      publicIp: '197.237.19.4',
      networkEndpoint: 'Mombasa, Nyali',
      uptimeDuration: '6:19 hrs',
    },
  },
];
